#!/usr/bin/env bats
# Tests for the idea-enhancer tooling:
#   - scripts/idea-enhancer/gather-candidates.sh  (mocks `gh` GraphQL — candidate filtering)
#   - scripts/idea-enhancer/post-enhancement.sh   (DRY_RUN path only — no network)
#
# Run with: bats tests/test_idea_enhancer.bats

setup() {
  ROOT="$(cd "$BATS_TEST_DIRNAME/.." && pwd)"
  ENH_DIR="$ROOT/scripts/idea-enhancer"
  TMP="$(mktemp -d)"
  MOCK_BIN="$TMP/bin"
  mkdir -p "$MOCK_BIN"
  CONTEXT="$TMP/context.json"
  LOG="$TMP/dry.jsonl"
  export PATH="$MOCK_BIN:$PATH"
  export GH_TOKEN="tok"
}

teardown() { rm -rf "$TMP"; }

# A `gh` mock that handles both the single-discussion query (when DISCUSSION_NUMBER
# is set) and the paginated discussions query (bulk scan path).
_install_gh_mock() {
  cat > "$MOCK_BIN/gh" <<'EOF'
#!/usr/bin/env bash
if [[ "$*" == *"discussion(number:"* ]]; then
  num="106"
  if [[ "$*" == *"number=101"* || "$*" == *"-F number=101"* ]]; then
    num="101"
  fi

  if [ "$num" = "106" ]; then
    cat <<'JSON'
{
  "data": { "repository": { "discussion": {
    "number": 106, "title": "Human idea B", "url": "u/106",
    "createdAt": "2026-06-02T00:00:00Z", "updatedAt": "2026-06-02T00:00:00Z",
    "closed": false, "category": { "name": "Ideas" },
    "author": { "login": "erin", "__typename": "User" },
    "labels": { "nodes": [] },
    "comments": { "totalCount": 0, "nodes": [] },
    "bodyText": "Another plain human idea."
  } } }
}
JSON
  else
    cat <<'JSON'
{
  "data": { "repository": { "discussion": {
    "number": 101, "title": "Human idea A", "url": "u/101",
    "createdAt": "2026-06-01T00:00:00Z", "updatedAt": "2026-06-01T00:00:00Z",
    "closed": false, "category": { "name": "Ideas" },
    "author": { "login": "alice", "__typename": "User" },
    "labels": { "nodes": [] },
    "comments": { "totalCount": 0, "nodes": [] },
    "bodyText": "A plain human idea."
  } } }
}
JSON
  fi
else
  cat <<'JSON'
{
  "data": { "repository": { "discussions": {
    "pageInfo": { "hasNextPage": false, "endCursor": "" },
    "nodes": [
      { "number": 101, "title": "Human idea A", "url": "u/101",
        "createdAt": "2026-06-01T00:00:00Z", "updatedAt": "2026-06-01T00:00:00Z",
        "closed": false, "category": { "name": "Ideas" },
        "author": { "login": "alice", "__typename": "User" },
        "labels": { "nodes": [] },
        "comments": { "totalCount": 0, "nodes": [] },
        "bodyText": "A plain human idea." },
      { "number": 102, "title": "Bot idea", "url": "u/102",
        "createdAt": "2026-06-01T00:00:00Z", "updatedAt": "2026-06-01T00:00:00Z",
        "closed": false, "category": { "name": "Ideas" },
        "author": { "login": "ideation-bot", "__typename": "Bot" },
        "labels": { "nodes": [] },
        "comments": { "totalCount": 0, "nodes": [] },
        "bodyText": "Generated by the ideation bot." },
      { "number": 103, "title": "Already enhanced idea", "url": "u/103",
        "createdAt": "2026-06-01T00:00:00Z", "updatedAt": "2026-06-01T00:00:00Z",
        "closed": false, "category": { "name": "Ideas" },
        "author": { "login": "bob", "__typename": "User" },
        "labels": { "nodes": [] },
        "comments": { "totalCount": 1, "nodes": [
          { "body": "Here is an enhancement.\n\n<!-- idea-enhancer:enhanced -->",
            "author": { "login": "github-actions" } } ] },
        "bodyText": "An idea that already has an enhancement comment." },
      { "number": 104, "title": "Not an idea", "url": "u/104",
        "createdAt": "2026-06-01T00:00:00Z", "updatedAt": "2026-06-01T00:00:00Z",
        "closed": false, "category": { "name": "General" },
        "author": { "login": "carol", "__typename": "User" },
        "labels": { "nodes": [] },
        "comments": { "totalCount": 0, "nodes": [] },
        "bodyText": "A general discussion, not an idea." },
      { "number": 105, "title": "Closed idea", "url": "u/105",
        "createdAt": "2026-06-01T00:00:00Z", "updatedAt": "2026-06-01T00:00:00Z",
        "closed": true, "category": { "name": "Ideas" },
        "author": { "login": "dave", "__typename": "User" },
        "labels": { "nodes": [] },
        "comments": { "totalCount": 0, "nodes": [] },
        "bodyText": "A closed idea." },
      { "number": 106, "title": "Human idea B", "url": "u/106",
        "createdAt": "2026-06-02T00:00:00Z", "updatedAt": "2026-06-02T00:00:00Z",
        "closed": false, "category": { "name": "Ideas" },
        "author": { "login": "erin", "__typename": "User" },
        "labels": { "nodes": [] },
        "comments": { "totalCount": 0, "nodes": [] },
        "bodyText": "Another plain human idea." }
    ]
  } } }
}
JSON
fi
EOF
  chmod +x "$MOCK_BIN/gh"
}

# ── gather-candidates: filtering ─────────────────────────────────────────────

@test "gather-candidates keeps only fresh, open, human-authored Ideas" {
  _install_gh_mock
  REPO="owner/repo" CONTEXT_PATH="$CONTEXT" run bash "$ENH_DIR/gather-candidates.sh"
  [ "$status" -eq 0 ]
  # Only #101 and #106 survive (bot/enhanced/non-Ideas/closed are dropped).
  [ "$(jq '.candidates | length' "$CONTEXT")" -eq 2 ]
  nums="$(jq -c '[.candidates[].number] | sort' "$CONTEXT")"
  [ "$nums" = "[101,106]" ]
}

@test "gather-candidates records repo and marker in the context" {
  _install_gh_mock
  REPO="owner/repo" CONTEXT_PATH="$CONTEXT" run bash "$ENH_DIR/gather-candidates.sh"
  [ "$status" -eq 0 ]
  [ "$(jq -r '.repo' "$CONTEXT")" = "owner/repo" ]
  [ "$(jq -r '.marker' "$CONTEXT")" = "<!-- idea-enhancer:enhanced -->" ]
}

@test "gather-candidates scopes to DISCUSSION_NUMBER when set" {
  _install_gh_mock
  REPO="owner/repo" CONTEXT_PATH="$CONTEXT" DISCUSSION_NUMBER="106" \
    run bash "$ENH_DIR/gather-candidates.sh"
  [ "$status" -eq 0 ]
  [ "$(jq '.candidates | length' "$CONTEXT")" -eq 1 ]
  [ "$(jq -r '.candidates[0].number' "$CONTEXT")" = "106" ]
}

@test "gather-candidates fails when REPO is missing" {
  _install_gh_mock
  # REPO can leak in from the surrounding environment; unset it explicitly so
  # the required-var guard is what's under test.
  CONTEXT_PATH="$CONTEXT" run env -u REPO bash "$ENH_DIR/gather-candidates.sh"
  [ "$status" -ne 0 ]
}

@test "gather-candidates fails when REPO lacks a slash" {
  _install_gh_mock
  REPO="noslash" CONTEXT_PATH="$CONTEXT" run bash "$ENH_DIR/gather-candidates.sh"
  [ "$status" -ne 0 ]
  [[ "$output" == *"owner/repo"* ]]
}

# ── post-enhancement: DRY_RUN path ───────────────────────────────────────────

@test "post-enhancement (DRY_RUN) logs the comment with the marker appended" {
  BODY="$TMP/body.md"
  printf 'A concrete enhancement to your idea.' > "$BODY"
  body_len=$(wc -c < "$BODY")
  DRY_RUN=1 DRY_RUN_LOG="$LOG" REPO="owner/repo" DISCUSSION_NUMBER="101" \
    BODY_PATH="$BODY" run bash "$ENH_DIR/post-enhancement.sh"
  [ "$status" -eq 0 ]
  grep -q '"op":"post_enhancement"' "$LOG"
  [ "$(jq -r 'select(.op=="post_enhancement") | .number' "$LOG")" = "101" ]
  # The posted body includes the original text plus the appended marker, so it
  # must be strictly longer than the raw body file.
  [ "$(jq -r 'select(.op=="post_enhancement") | .body_len' "$LOG")" -gt "$body_len" ]
}

@test "post-enhancement fails on a missing/empty body" {
  DRY_RUN=1 DRY_RUN_LOG="$LOG" REPO="owner/repo" DISCUSSION_NUMBER="101" \
    BODY_PATH="$TMP/nope.md" run bash "$ENH_DIR/post-enhancement.sh"
  [ "$status" -ne 0 ]
  [[ "$output" == *"missing or empty"* ]]
}

@test "post-enhancement fails when REPO lacks a slash" {
  BODY="$TMP/body.md"
  printf 'A concrete enhancement.' > "$BODY"
  DRY_RUN=1 DRY_RUN_LOG="$LOG" REPO="noslash" DISCUSSION_NUMBER="101" \
    BODY_PATH="$BODY" run bash "$ENH_DIR/post-enhancement.sh"
  [ "$status" -ne 0 ]
  [[ "$output" == *"owner/repo"* ]]
}
