#!/usr/bin/env bash
# Configurable via: STUB_ENGINE_RESPONSE, STUB_ENGINE_EXIT, STUB_ENGINE_DELAY
while [[ $# -gt 0 ]]; do
  case "$1" in
    --print|--model|--permission-mode|--allowed-tools|--disallowed-tools|--max-turns)
      shift; shift ;;
    *) shift ;;
  esac
done
sleep "${STUB_ENGINE_DELAY:-0}"
printf '%s\n' "${STUB_ENGINE_RESPONSE:-stub engine response}"
exit "${STUB_ENGINE_EXIT:-0}"
